services:

  tg_bot:
    build: .
    depends_on:
      - tg_database
#    command: sh -c 'sleep 35'
    restart: on-failure

  tg_database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    expose:
      - "5433"
    command: -p 5433

volumes:
  pgdata:

networks:
  tg_database:
    driver: bridge